=== htho/wibbles/schema/spriteset.json
{
  "$ref": "#/definitions/Spriteset",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "AnimatedSprite": {
      "additionalProperties": false,
      "properties": {
        "index": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              }
            },
            "required": [
              "x",
              "y"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "time": {
          "type": "number"
        }
      },
      "required": [
        "time",
        "index"
      ],
      "type": "object"
    },
    "Meta": {
      "additionalProperties": false,
      "properties": {
        "author": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "version": {
          "type": "number"
        }
      },
      "required": [
        "name",
        "author",
        "version"
      ],
      "type": "object"
    },
    "MultiSprite": {
      "additionalProperties": false,
      "properties": {
        "C": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ],
          "description": "center"
        },
        "E": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ]
        },
        "H": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ],
          "description": "horizontal"
        },
        "N": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ]
        },
        "NE": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ]
        },
        "NW": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ]
        },
        "S": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ]
        },
        "SE": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ]
        },
        "SW": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ]
        },
        "V": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ],
          "description": "vertical"
        },
        "W": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ]
        },
        "middle": {
          "anyOf": [
            {
              "$ref": "#/definitions/StaticSprite"
            },
            {
              "$ref": "#/definitions/AnimatedSprite"
            }
          ]
        }
      },
      "type": "object"
    },
    "Sprite": {
      "anyOf": [
        {
          "$ref": "#/definitions/MultiSprite"
        },
        {
          "$ref": "#/definitions/StaticSprite"
        },
        {
          "$ref": "#/definitions/AnimatedSprite"
        }
      ]
    },
    "Spriteset": {
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "file": {
          "type": "string"
        },
        "meta": {
          "$ref": "#/definitions/Meta"
        },
        "sprites": {
          "additionalProperties": {
            "$ref": "#/definitions/Sprite"
          },
          "type": "object"
        },
        "widthHeight": {
          "type": "number"
        }
      },
      "required": [
        "$schema",
        "meta",
        "file",
        "widthHeight",
        "sprites"
      ],
      "type": "object"
    },
    "StaticSprite": {
      "additionalProperties": false,
      "properties": {
        "index": {
          "additionalProperties": false,
          "properties": {
            "x": {
              "type": "number"
            },
            "y": {
              "type": "number"
            }
          },
          "required": [
            "x",
            "y"
          ],
          "type": "object"
        }
      },
      "required": [
        "index"
      ],
      "type": "object"
    }
  }
}

=== htho/wibbles/data/sprites/oga--zelda-like-tilesets-and-sprites/overworld.json
{
    "$schema": "../../../schema/spriteset.json",
    "meta": {
        "author": "htho",
        "name": "zelda-like-overworld",
        "version": 1
    },
    "file": "gfx/Overworld.png",
    "widthHeight": 16,
    "sprites": {
        "grass": {"index": {"x": 0, "y": 0}},
        "log": {
            "W": {"index": {"x": 3, "y": 5}},
            "H": {"index": {"x": 4, "y": 5}},
            "E": {"index": {"x": 5, "y": 5}}
        },
        "stones": {"index": {"x": 11, "y": 23}},
        "flowers": {"index": {"x": 0, "y": 8}},
        "fence": {
            "H": {"index": {"x": 4, "y": 17}},
            "V": {"index": {"x": 4, "y": 18}},
            "NE": {"index": {"x": 3, "y": 17}},
            "NW": {"index": {"x": 2, "y": 17}},
            "SW": {"index": {"x": 2, "y": 18}},
            "SE": {"index": {"x": 3, "y": 18}},
            "N": {"index": {"x": 0, "y": 17}},
            "S": {"index": {"x": 0, "y": 18}},
            "W": {"index": {"x": 0, "y": 19}},
            "E": {"index": {"x": 1, "y": 19}}
        },
        "well": {
            "NW": {"time": 1000, "index": [{"x": 22, "y": 9}, {"x": 25, "y": 9}, {"x": 28, "y": 9}]},
            "N": {"time": 1000, "index": [{"x": 23, "y": 9}, {"x": 26, "y": 9}, {"x": 29, "y": 9}]},
            "NE": {"time": 1000, "index": [{"x": 24, "y": 9}, {"x": 27, "y": 9}, {"x": 30, "y": 9}]},
            "W": {"time": 1000, "index": [{"x": 22, "y": 10}, {"x": 25, "y": 10}, {"x": 28, "y": 10}]},
            "C": {"time": 1000, "index": [{"x": 23, "y": 10}, {"x": 26, "y": 10}, {"x": 29, "y": 10}]},
            "E": {"time": 1000, "index": [{"x": 24, "y": 10}, {"x": 27, "y": 10}, {"x": 30, "y": 10}]},
            "SW": {"time": 1000, "index": [{"x": 22, "y": 11}, {"x": 25, "y": 11}, {"x": 28, "y": 11}]},
            "S": {"time": 1000, "index": [{"x": 23, "y": 11}, {"x": 26, "y": 11}, {"x": 29, "y": 11}]},
            "SE": {"time": 1000, "index": [{"x": 24, "y": 11}, {"x": 27, "y": 11}, {"x": 30, "y": 11}]}
        }
    }
}
